### ISSUE TITLE
Generating a Occupancy Grid using Hokuyo Laser Range Finder

### ISSUE THREAD

**Issue by ktiwari9** [rhololkeolke/eecs_600_robot_project1#1]
Hi there,
I am using ROS Hydro with Hokuyo mounted on a Husky A200. I want to be able to take the readings from the Hokuyo as an input and be able to visualize a Occupancy Grid in RViZ. Is it possible to use your file named 2d_map_creator.cpp for this purpose ? Would I need to change something or can I use it as it is ?

**Comment by rhololkeolke** [comment]
Its been a while since I've worked with this code, but I think it should work. You might have to change the frames in the callback functions though. I had them set to the Atlas robot frames. Other than that you should just have to set the right parameters and remap the correct topics. I've added a BSD license to the project so you can use it without an legal issues.

I'm a bit hazy on the details but looking at the code and from what I remember the parameters and topics are as follows:

The parameters are:
- **width** - int - the number of cells in x direction of occupancy grid
- **height** - int - the number of cells in y direction of occupancy grid
- **x_offset** - double - moves the coordination location with respect to the lower left corner of the occupancy grid
- **y_offset** - double - same as x_offset but in y direction

The subscribers are:
- **laser/points** - for the PointCloud2 from the lasers

The map is published to "/map"

If you have any issues I can try and help and if it does work for you, let me know. It would be cool if this was useful for more than just a class project.

Best of luck,
Devin
